### ISSUE TITLE
Publishing received and approved files as build artifacts

### ISSUE THREAD

**Issue by michaelnoonan** [droyad/Assent#1]
When the tests fail on a build server, it is really convenient if the diff can be investigated without needing to remote onto the machine.

We do this with TeamCity by publishing the two files as artifacts.

It would be nice to add a callback you can hook into when a test fails, which passes the full path to the files, so you can add your own logic for your build server of choice.

What do you think?

**Comment by droyad** [comment]
You could do one of three things:
- The received files are now left behind on failing tests in non-interactive mode, so include those as artefacts in your build
- Implement `IReporter` and set that using `Configuration.UsingReporter(IReporter)` if running on the build server
- `Configuration.UsingReporter(Action<string,string>)` has been added, so again you could pass a custom delegate if running on the build server
