### ISSUE TITLE
Add env var to allow accepting everything by default

### ISSUE THREAD

**Issue by masaeedu** [droyad/Assent#12]
I'm using this library to basically hold functionality in place in a large legacy app I'm refactoring. The current behavior of the application, for better or worse, is what I want to preserve.

To do this I'm generating and running thousands of approval-based tests that describe how data interacts with the application, which means it's pretty painful to manually go through and approve every diff using my diff tool. I need some kind of option to approve everything the first time I run it, possibly an env var.

Would this be a change you'd be open to having?

**Comment by droyad** [comment]
Could you set the `AssentNonInteractive` env variable (https://github.com/droyad/Assent/wiki#automated-builds) and then run a script to copy all `.received` to `.approved`?

**Comment by droyad** [comment]
Or the other option is to write a `IReporter` the just copied the contents of `recievedFile` into `approvedFile`

**Comment by masaeedu** [comment]
Setting `AssentNonInteractive` seems to cause my tests to blow up with:

```
Message: Assent.AssentApprovedFileNotFoundException : The assent file 'D:\depot\git\autotest\Framework.Tests\snapshots\Config\LinuxAgent\Linux-LVR-Nto1\linux-lvr-nto1.suites\CanReserialize.approved.txt' was not found
```

**Comment by masaeedu** [comment]
Using `.UsingReporter(File.Copy)` however works like a charm 😄. Might be a good idea to put that in the docs.

**Comment by masaeedu** [comment]
@droyad There is some hardcoded logic in `Engine.cs` that tries to ensure that the "approved" file exists first whenever you're running things in non-interactive mode, and otherwise throws `AssentApprovedFileNotFoundException`. This results in the strange behavior where unattended copying of files from `approvedFile` to `receivedFile` only works if you *disable* `AssentNonInteractive`.
