### ISSUE TITLE
Beyond Compare on Linux/BSD/Mac doesn't open in solo mode

### ISSUE THREAD

**Issue by jburger** [droyad/Assent#25]
Looks like on mac and linux environments that any flags passed to `bcompare` need to be supplied using a single `-` characters, whereas on windows `/` is used. Since Assent leans on the `/solo` flag, this tries to open as a 3-way merge on Linux.
From [the docs](https://www.scootersoftware.com/v4help/index.html?command_line_reference.html)
![image](https://user-images.githubusercontent.com/579657/83827968-ace88b00-a71e-11ea-9e38-bb58d9dd8489.png)

**Comment by droyad** [comment]
Done
