### ISSUE TITLE
Creating a configuration throws on OSX

### ISSUE THREAD

**Issue by recumbent** [droyad/Assent#3]
When you create a configuration it creates a DiffReporter

When you create a DiffReporter it creates instances of the default comparers and somewhere in there its throwing an error when run on OSX.

So the custom configuration is basically ignored...

I need to dig a bit further to properly understand what part of the constructor sequence is causing the error.

**Comment by droyad** [comment]
@recumbent Thanks for the report. I've fixed it up and published a new package.

The default Diff programs are now only set on Windows.

Problem was one of the diff programs was trying to concatentat a path from an environment variable that was null on non-windows platforms.

**Comment by recumbent** [comment]
That's awesome, thanks!

I'd spotted the cause (having pulled down the code to hack round the problem) - just not had any opportunity to even think about how it might properly be addressed

**Comment by droyad** [comment]
If you do end up creating a reporter for MacOS, I'd be happy to add it.

**Comment by Koleja** [comment]
@droyad is it possible to use custom configuration of the Reporter with use `var reporter = new DiffReporter(DiffReporter.DefaultDiffPrograms);` on Mac? I'm trying to run tests on already set up project and it throws errors `System.Exception : Could not find a diff program to use`.

**Comment by droyad** [comment]
Yes, you should be able to use the `WithReporter` method on the configuration to use a custom reporter instead of the default `DiffReporter`. You'll likely just need to implement the `IDiffProgram` and pass it to the `DiffReporter` constructur
See https://github.com/droyad/Assent/blob/master/src/Assent/Configuration.cs#L77
