### ISSUE TITLE
2 wiki links don't work

### ISSUE THREAD

**Issue by attw00d** [droyad/Assent#32]
These two links don't work.

1. https://github.com/droyad/Assent/wiki#Comparer
2. https://github.com/droyad/Assent/wiki/How-It-Works#Naming

In markdown, they need to be updated to;
1. https://github.com/droyad/Assent/wiki/Comparison
2. https://github.com/droyad/Assent/wiki/Naming

**Comment by droyad** [comment]
Thanks, fixed
