### ISSUE TITLE
VsCode diff reporter not working.

### ISSUE THREAD

**Issue by dazinator** [droyad/Assent#9]
In my test, I am using a reporter that has the vscode diff program in:
![image](https://user-images.githubusercontent.com/3176632/30336361-dde267b6-97dc-11e7-84d4-71b4e8c33e42.png)

However the `Assent` throws an exception that it could not find a diff program to use:

```
System.Exception: 'Could not find a diff program to use'
```

Yet if I look at the searchpaths to `Code.exe` it is correct.

Not sure what I am doing wrong?

Here is the configuration code:

```
            // Now verify the xml looks good.
            var configuration = new Configuration().UsingExtension(".xml");
            var programs = new IDiffProgram[] {
                    new VsCodeDiffProgram()
                }
                .Concat(Assent.Reporters.DiffReporter.DefaultDiffPrograms)
                .ToArray();
            var reporter = new Assent.Reporters.DiffReporter(programs);
            configuration.UsingReporter(reporter);           

            // This throws.
            this.Assent(xmlStringBuilder.ToString(), configuration);

```

And I am running the test under netcoreapp2.0

**Comment by dazinator** [comment]
Have had a quick look and figured out the problem.

You need to do the following:

```
   configuration = configuration.UsingReporter(reporter);
```

rather than what is suggested in the wiki:

```
 configuration.UsingReporter(reporter);

```

This is because `UsingReporter` doesn't appear to mutate the configuratioin instance, but rather returns a new instance based on the old instance, but with the modified state. So you need to capture its return value when calling these methods.

**Comment by droyad** [comment]
@dazinator I've updated the wiki to make this clearer.
